### ISSUE TITLE
Add KGX Member Category

### ISSUE THREAD

**Issue by nivu** [kgex/bigbfe#57]
KGX Rookie (Previously Nano)
KGX Pro (Previously Pro)
KGX Veteran
KGX Chief (Previously Leads)
KGX Captain

backend field

"category"

-----Options-----
ROOKIE
PRO
VETERAN
CHIEF
CAPTAIN

**Comment by Aribaskar-jb** [comment]
@Sathasivamthirumoorthi has completed this task sir
